---
name: mkdocs-publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Poetry
        run: pip install poetry
      - name: Install docs deps
        run: poetry install --no-interaction --no-root --with docs
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV
      - name: Build & deploy
        run: poetry run mkdocs gh-deploy --force
